### ISSUE TITLE
Confirm re-run dialog button gets confused when there are transactions with disabled or deleted channels

### ISSUE THREAD

**Issue by rcrichton** [jembi/openhim-console#277]

**Comment by BMartinos** [comment]
Is it possible to get a screenshot of this to better indicate the problem?

**Comment by rcrichton** [comment]
Basically what happen is that when you click the re-run button on the re-run dialog it doesn't clsoe the modal or report an error. It just says open.

**Comment by BMartinos** [comment]
I think something is going a bit wrong on that page. I see the check boxes are being displayed for transactions that are displayed/deleted. They should not be allowed to rerun those transactions due to the channel status. That also explains the popup modal not doing anything as it gets a 400 back from the server rejecting those transactions.

Will look at why its not removing the checkboxes
