### ISSUE TITLE
Rerun transactions not updating as rerun, including icon.

### ISSUE THREAD

**Issue by napiergit** [jembi/openhim-console#356]

**Comment by rcrichton** [comment]
This seems to work for me. Could you give and example of what you are doing, it may be failing in a particular case.

**Comment by napiergit** [comment]
Look for this error in production:  cat /var/log/openhim-core.log | grep -C10 ValidationError

The mongoose schema validation is failing for some reason.  If I remove "TransactionSchema.request.timestamp.required: true" it works (serious hack).  I'm still trying to find an explanation in the mongoose documentation, it could be the .save() mongoose function.

This happens occasionally when a failed transaction is rerun.

**Comment by rcrichton** [comment]
Interesting. Would you be able to pull out a sample of this error from the logs that doesn't have an sensitive information in it.

**Comment by napiergit** [comment]
This is what's happening:

A transaction fails because of connectivity issues.  The orchestrations are thus not completed.  As a result there is no request (nor request.timestamp) in one of the orchestrations and this causes the [Schema] (https://github.com/jembi/openhim-core-js/blob/master/src/model/transactions.coffee#L28) validation to fail.    

Possible solutions:
- [Remove the required field in the request schema](https://github.com/jembi/openhim-core-js/blob/master/src/model/transactions.coffee#L15)
- [Change the request schema for orchestrations](https://github.com/jembi/openhim-core-js/blob/master/src/model/transactions.coffee#L28)
- Maybe a newer version of mongoose would pass the validation schema, because it is strange that it fails a request.timestamp requirement when there is no request object.

**Comment by rcrichton** [comment]
Thanks @napiergit that makes sense. I think the problem lies in the mediator that is doing the orchestration, they shouldn't be sending us invalid responses. They should always include a request even if the request is un-successful.

Although, we should also handle the error graceful in the OpenHIM and not fail to update the transaction during a re-run. When the parent transaction fails in the first case does it get stored with an invalid orchestration? So, does the this error only occur  when the transaction is re-run which already contains bad data?

@hnnesv what are your thought on this problem?

**Comment by napiergit** [comment]
Thanks @rcrichton, to answer your question, yes to both.

**Comment by hnnesv** [comment]
@rcrichton yeah agree looks like a mediator problem - although _technically_ atm the responses aren't invalid since our mediator API doesn't mandate the requirement.

So agree we need to deal with this in core somehow (we can still further restrict the mediator format, but I guess that would mean a major version bump).

This does raise the point though about how we deal with errors regarding mediator responses, seeing as we can't respond back to a mediator and let them know it was invalid - should the HIM make a best effort to deal with what it has? the transaction's already run so we can't really reject it...

I'm okay with the first option to remove the required clause on the schema as a first solution.

**Comment by rcrichton** [comment]
There may be a good reason why `request.timestamp` is required. I'm not sure we should relax that constraint. It may break other parts of the system that expect it. 

Perhaps we need to catch errors and in mediator responses and somehow note that the response could not be parsed. We would want mediator errors to somehow be visible to the user.

**Comment by rcrichton** [comment]
The issue seems be that mongoose populates objects in the schema with empty object when you create an object via `new Transaction({...})`. So we end up with an orchestration object like:

```
{ name: 'Orchestrator Mediator',
       _id: 56b8974a2225f72200913249,
       response: [Object],
       request: {} } ],
```

even though the request was never set. This causes mongoose to complain that  the `request.timestamp` property is missing.
